### ISSUE TITLE
gmsh issue

### ISSUE THREAD

**Issue by weich97** [jerabaul29/Cylinder2DFlowControlDRLParallel#10]
Hi Jean,

     Do you know how to fix the gmsh issue in your code. I have the following error:

gmsh: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

    Even if I used the correct absolute path for the gmsh, I still have the above error. It seems that the container does not have a gmsh inside. 

     Hope you can provide some suggestions. Thanks!

Best,

Weicheng

**Comment by jerabaul29** [comment]
Mmmh, I wrote / used this code a long time ago, I do not fully remember now. I *thought* I remembered that the gmsh in the right version was available in the docker image; are you sure you use the docker container for this project, not the singularity container from https://github.com/jerabaul29/Cylinder2DFlowControlDRL ?

You could also try something similar to what is said there in the gmsh section, ie exporting the path to Gmsh when you spin a container from the image: https://github.com/jerabaul29/Cylinder2DFlowControlDRL .

**Comment by jerabaul29** [comment]
@thw1021 you used this code more recently than me, maybe you remember better, could you help here? :) . (@weich97 you can have a look at the code and video there see if this helps https://github.com/thw1021/Cylinder2DFlowControlGeneral ).

**Comment by weich97** [comment]
Jean, 

     I just installed a lot of dependencies in the container. I think the issue is related to some gmsh GUI stuff in the docker container. I think it is fine to have this issue, because if we can generate .msh from .geo then it is ok (and I can do that). yeah, I am using the docker container.  I will update this ticket if I can find another method to fix this. Thanks!
     
Best,

**Comment by thw1021** [comment]
I remembered this error. If you used the `gmsh` binary file, you can try `sudo apt-get install gmsh`.

**Comment by jerabaul29** [comment]
Ok, so just install gmsh interactively in the container.
