### ISSUE TITLE
Can you kindly help me please.

### ISSUE THREAD

**Issue by kamyd** [jerabaul29/Cylinder2DFlowControlDRLParallel#11]
Hello DR and good day,
Thank you very much for sharing your work, I am using your code for my master's degree final project, and I started using your code before the new ones publication, now I have to change the geometry from circle to anything else. 
I know that i have to change the template_geo file (and read the non parallel issues) and I opened it using gmsh GUI but unfortunately I cant change it (when i do anything using GUI it simply appends a command at the end of the code) and I cant understand the gmsh code itself as it has extra parameters! 
I am stuck at the end of my project can you please help me in any way? 

Thank you for your answer

**Comment by jerabaul29** [comment]
Hi,

I am sorry but this is not an issue related to the core of this work - this is a question about gmsh use and gmsh scripting. Please learn gmsh (there are many good tutorials and documentation online, for example https://gmsh.info/doc/texinfo/gmsh.html ). I will unfortunately not have time to support on this.

Closing as out of scope.
