### ISSUE TITLE
cylinder2dflowcontrol_Parallel_v1.tar not found

### ISSUE THREAD

**Issue by zonexo** [jerabaul29/Cylinder2DFlowControlDRLParallel#12]
Hi,

I tried to download cylinder2dflowcontrol_Parallel_v1.tar but it is not found:

```
(dmd) user@DELL7610:~$ wget https://folk.uio.no/jeanra/Informatics/cylinder2dflowcontrol_Parallel_v1.tar
--2023-06-27 14:22:19--  https://folk.uio.no/jeanra/Informatics/cylinder2dflowcontrol_Parallel_v1.tar
Resolving folk.uio.no (folk.uio.no)... 129.240.118.92, 2001:700:100:118::92
Connecting to folk.uio.no (folk.uio.no)|129.240.118.92|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://folk.universitetetioslo.no/jeanra/Informatics/cylinder2dflowcontrol_Parallel_v1.tar [following]
--2023-06-27 14:22:20--  https://folk.universitetetioslo.no/jeanra/Informatics/cylinder2dflowcontrol_Parallel_v1.tar
Resolving folk.universitetetioslo.no (folk.universitetetioslo.no)... 129.240.118.41, 2001:700:100:118::41
Connecting to folk.universitetetioslo.no (folk.universitetetioslo.no)|129.240.118.41|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-27 14:22:22 ERROR 404: Not Found.

(dmd) user@DELL7610:~$ cylinder2dflowcontrol_Parallel_v1.tar
cylinder2dflowcontrol_Parallel_v1.tar: command not found
```

Both addresses are not able to download the file.
Can you check what's the problem?

Thanks.

**Comment by jerabaul29** [comment]
folk.uio.no was taken down several years ago. Now the container is hosted directly as several git-lfs segments available on this repo: see the readme: https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel#getting-started . Please check out the latest version of the git repo / use the segments from there :) . I think I removed the link to the folk.uio.no hosting quite a few years ago from this readme - not sure where you got this link from, can you let me know if there are still references to this old hosting solution lying around, so I can remove them? :) .

Closing, but if you have problems feel free to re-open / ask for help.
