### ISSUE TITLE
git clone https://github.com/jerabaul29/Cylinder2DFlowControlWithRL_collaboration_Jonathan.git

### ISSUE THREAD

**Issue by lzlsjwl** [jerabaul29/Cylinder2DFlowControlDRLParallel#13]
Dear professor,

I hope this message finds you well. I encountered an issue while trying to clone the repository "Cylinder2DFlowControlWithRL_collaboration_Jonathan" from GitHub using the following command:

git clone https://github.com/jerabaul29/Cylinder2DFlowControlWithRL_collaboration_Jonathan.git
However, I received the following error message:

remote: Repository not found.
fatal: repository 'https://github.com/jerabaul29/Cylinder2DFlowControlWithRL_collaboration_Jonathan.git/' not found

I have carefully checked the URL and confirmed that it is correct. Is it possible that the repository has been deleted or renamed? I would greatly appreciate any assistance or guidance you can provide to resolve this issue.

Thank you in advance for your attention to this matter.

Best regards

**Comment by jerabaul29** [comment]
Hi,

Not sure how you got the URL of this repository - it has never been made public and has not been used for 5 years, weird that you got the address to it. Can I ask where you got this URL from?

Anyways, the repo in question was a copy of an old version of https://github.com/jerabaul29/Cylinder2DFlowControlDRL . So you should use https://github.com/jerabaul29/Cylinder2DFlowControlDRL instead, and possibly the follow up repos, such as https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel , https://github.com/thw1021/Cylinder2DFlowControlGeneral , https://github.com/venturi123/DRLinFluids (there have been quite some developments and papers + code released over the last few years).

Closing, but feel free to re-open if something is unclear.

Best,

Jean

**Comment by lzlsjwl** [comment]
> Hi,
> 
> Not sure how you got the URL of this repository - it has never been made public and has not been used for 5 years, weird that you got the address to it. Can I ask where you got this URL from?
> 
> Anyways, the repo in question was a copy of an old version of https://github.com/jerabaul29/Cylinder2DFlowControlDRL . So you should use https://github.com/jerabaul29/Cylinder2DFlowControlDRL instead, and possibly the follow up repos, such as https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel , https://github.com/thw1021/Cylinder2DFlowControlGeneral , https://github.com/venturi123/DRLinFluids (there have been quite some developments and papers + code released over the last few years).
> 
> Closing, but feel free to re-open if something is unclear.
> 
> Best,
> 
> Jean

Hi,Jean

I appreciate your response and clarification regarding the URL. I apologize for any confusion caused by using the incorrect URL. I obtained the URL from the README file in the Docker folder of the repository.

Thank you for providing the correct URL for the repository: https://github.com/jerabaul29/Cylinder2DFlowControlDRL. I will make sure to use this repository instead. Additionally, I will explore the follow-up repositories you mentioned, such as https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel, https://github.com/thw1021/Cylinder2DFlowControlGeneral, and https://github.com/venturi123/DRLinFluids, to stay updated with the latest developments and papers in this field.

Once again, I appreciate your assistance and prompt response.

Best regards
