### ISSUE TITLE
single_runner.py confusion

### ISSUE THREAD

**Issue by ruyigolden-cudgel** [jerabaul29/Cylinder2DFlowControlDRLParallel#14]
Hi, @jerabaul29 
&nbsp;&nbsp;Thanks for your code, I'm using your code for my control case. But I ran into a problem when running **_single_runner.py_** to test my best model. When **_single_runner.py_** finished running and I used paraview to check out the VTU file in the **_results_** folder, I found that the test environment was started with the end of the flow simulation without control. Meanwhile, jets were involved in test process. 
&nbsp;&nbsp;My confusion is that why my test environment is not starting with the flow entering the channel inlet from the left side? What might be wrong to cause this condition? And what i could do to get test environment started at the flow entering the channel. I really hope I could get your help.

**Comment by jerabaul29** [comment]
I am not sure of what you mean - do you mean that you are surprised that the test environment flow case starts from the baseline state, i.e. the fully developed flow? This is actually the point of the code as it is developed if this is what you ask about - i.e., we look into how to control the flow "fully developed". Think about "the cylinder is in the flow and has been for a while, and you suddenly turn on the control".

If what you mean is "I am interested in what happens / how the control should look like starting with the cylinder in the flow in a state of rest", this is a different case, that we do not look into here. This would mean adding a transient, which could be a bit tricky I suppose (nothing impossible to do, but this would have to be done "right": i.e. have somehow the flow developing around the cylinder from the state of uniform velocity u=v=0, which would require careful handling).

So the point of this code is to look into the control of the cylinder, starting from the "established flow", not the control of the cylinder "starting from the state of rest and accelerating in the flow", is this is what you mean. This is just a different fluid mechanics problem, that could be interesting to study on its own of course :) .

If this answers your question, please close the issue :) .

**Comment by ruyigolden-cudgel** [comment]
Thanks for your answer！This helps me to fully understand the whole process！:)
