### ISSUE TITLE
Question about hyperparameters

### ISSUE THREAD

**Issue by TRPrasanna** [jerabaul29/Cylinder2DFlowControlDRLParallel#16]
Hi, I had a question about the hyperparameters, in particular the batch size. In the file Cylinder2DFlowControlWithRL/launch_parallel_training.py, line 54 reads

```
    batch_size=20, learning_rate=1e-3, subsampling_fraction=0.2, optimization_steps=25,
```
Here, does the batch size correspond to 20 episodes and 1600 actions (80 actuations per episode)?

**Comment by jerabaul29** [comment]
yes, batch size unit is number of episodes in tensorforce; see:

https://tensorforce.readthedocs.io/en/latest/agents/ppo.html?highlight=batch_size

"
batch_size ([parameter](https://tensorforce.readthedocs.io/en/latest/modules/parameters.html), int > 0) – Number of episodes per update batch (required).
"
