### ISSUE TITLE
change the parameters

### ISSUE THREAD

**Issue by turtle-mei** [jerabaul29/Cylinder2DFlowControlDRLParallel#4]
Hi ,professor!
      recently ,I change the way the run your code , I chose to use your parallel code . but I am confused， how can i change the geo or other parameters?  Looking forward to getting your reply,thank you.

**Comment by turtle-mei** [comment]
i think i solve it .

**Comment by jerabaul29** [comment]
Ok, great, as usual feel free to ping me if you have any question :) 

By the way, were you able to download and reconstruct the docker container from fragments as presented in the Readme? :) .

A small note: this code is perfectly functional, especially thanks to the docker container, but of course it starts to be a bit old. So if / when you start a new project from scratch, you may consider whether you like better to use further this container and code, or start from a 'white sheet' and the newest tensorforce version :) .

PS: I am not a professor ;)
