### ISSUE TITLE
How to visualize the test process?

### ISSUE THREAD

**Issue by nicehiro** [jerabaul29/Cylinder2DFlowControlDRLParallel#5]
Hi, your work is really great!

I'm using your work recently, but I couldn't visualize the training or testing process.

When the training process finished, I couldn't find vtu files in the result directory. And When I run the test file `single_runner.py`, I can only get the CSV file.

Then I change the `plot` flag to `True` in `single_runner.py`, it just stuck after 1 EP.

**Comment by jerabaul29** [comment]
Hi,

Many thanks for your kind words!

The level of output / plotting etc is controlled by a few parameters. There are usually de activated by default, to save disk place, but you can turn them on when you want (as you tried putting plot to True). Note that if you turn these on for all simulations, it may be a lot of data / figures, so you may want to turn these on specifically for some simulations. This should already be taken care out here though (seems like I do not propagate the plot parameter there; you may try to set it to true for the rank 0):

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/b58f8ab212fd8a841572186ba588977a6bd8aacf/Cylinder2DFlowControlWithRL/simulation_base/start_one_server.py#L51-L63

which in turn is set inside this:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/b58f8ab212fd8a841572186ba588977a6bd8aacf/Cylinder2DFlowControlWithRL/simulation_base/env.py#L107-L117

which in turn applies here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/b58f8ab212fd8a841572186ba588977a6bd8aacf/Cylinder2DFlowControlWithRL/Env2DCylinder.py#L778-L780

Sorry for quite a few layers of indirection...

Regarding the dumping of the 2D velocity fields. This is commented at the moment as this is using a lot of hard disk, but you can put it on again here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/b58f8ab212fd8a841572186ba588977a6bd8aacf/Cylinder2DFlowControlWithRL/Env2DCylinder.py#L696-L706

Regarding your issue with setting plot to true; I wonder if this is a problem with your machine setup. The container can abstract quite a lot, but still it is the host machine that renders the figures if I remember well. So if you have some issues with plotting freezing the whole thing, may be a good idea to try instead to 1) disable plotting 2) set up velocity field dumping instead directly in the code. The vtk files should then live in the independent environment folders.

**Comment by jerabaul29** [comment]
This is a mess, sorry for that... This is because this was a research project, and we did not know in advance where we wanted to go, so a lot of it got hacked and there is a lot of technical debt. We just never got time to clean up.

**Comment by jerabaul29** [comment]
Another point: usually, the "big" data dumping happens when evaluating the best case network as a single run case. See: 

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel/blob/master/Cylinder2DFlowControlWithRL/single_runner.py

This does should dump the fields if I remember well.

**Comment by nicehiro** [comment]
@jerabaul29 Thanks. I'll try it later.
