### ISSUE TITLE
Code Errors

### ISSUE THREAD

**Issue by Arei1997** [jerabaul29/Cylinder2DFlowControlDRLParallel#7]
The python codes can't be run , there are many errors

**Comment by jerabaul29** [comment]
This code has been used by many different people over different OSes and architectures and over many years, so I am quite confident it does work well.

Which environment are you running the code into? Are you using the docker container to run the code?

**Comment by Arei1997** [comment]
I have never used docker so i got confused, i tried running just the python scripts in pycharm and VSC however for some reason i cant figure out how this happens

**Comment by jerabaul29** [comment]
It will not work without using the docker container I provide. Read the Readme, follow the instructions there, learn a bit of docker to be able to run the code, and things will work then :) .

Closing.
